### ISSUE TITLE
further autoaim tweaks

### ISSUE THREAD

**Issue by surytrap** [cactusbento/ULTRAUnNerf#1]
is it possible to make autoaim ignore enemies (to only ever work on coins/cores etc)

**Comment by cactusbento** [comment]
Yes.

The toggles are defined here (Just under the mod's toggle in Ultratweaker):
https://github.com/cactusbento/ULTRAUnNerf/blob/7340858718631aff2ed0a128ef5f529e40d3393c/Tweaks/autoaimimproved.cs#L34-L52

Consider this truth table when using the toggles:
https://github.com/cactusbento/ULTRAUnNerf/blob/7340858718631aff2ed0a128ef5f529e40d3393c/Tweaks/autoaimimproved.cs#L104-L108
